### PR TITLE
docs: update license copyright

### PR DESCRIPTION
**Pull request by Aaqilyousuf**
Updated license copyright year to **2024**

### CODE REVIEW

**Review by Aaqilyousuf — COMMENTED** [review]
successfully changed the year

**Comment by VerteDinde** [comment]
Hey @Aaqilyousuf, thanks for the PR! Could you also change the copyright in the website footer, as requested here?: https://github.com/electron/website/issues/509#issuecomment-1952554316 Happy to answer any questions 🙂

**Comment by Aaqilyousuf** [comment]
thanks for your reply, i'm new to open source contribution. i got some error while running the website locally it say 
**Error: Timed out waiting for API structure content**, what should i do

**Comment by VerteDinde** [comment]
Looking here, I assumed the year was hardcoded, but it looks like it should be regenerated here: https://github.com/electron/website/blob/3a0a0bad3398f4d72335cc6cb42c99b5676550fc/docusaurusConfig.ts#L182 We can handle that as maintainers 😄 Thanks!

**Review by VerteDinde — APPROVED** [review]

**Pull request merged**
