### PR TITLE
Updated examples in security guide

### PR DESCRIPTION
**Pull request by LeUser111**
As described in the issue, I've added some context and additional comments to the given examples for denying permissions and setting a CSP.

I've adjusted the examples according to my findings - I hope the new examples are correct!

### CODE REVIEW

**Comment by LeUser111** [comment]
I must have missed the option to link the pull request to my issue. The pull request belongs to [https://github.com/electron/website/issues/613](https://github.com/electron/website/issues/613)

**Comment by MarshallOfSound** [comment]
Hey @LeUser111, I haven't actually reviewed the content of this PR, but our docs are actually maintained in the core `electron/electron` repository 🤔 

https://github.com/electron/electron/tree/main/docs

So you probably want to make this PR over there

**Comment by LeUser111** [comment]
@MarshallOfSound Thanks for the info! Should I move the related issues (#613 and #615) to `electron/electron` as well?

**Comment by erickzhao** [comment]
@LeUser111 I'll ask someone with write permissions to `electron/electron` to transfer the issue over. :)

**Pull request closed without merging**
