### PR TITLE
changed the default design of 404 error page

### PR DESCRIPTION
**Pull request by Aryangp**
# Changed the designed of 404 page 
## Image of the new 404 error page that I made
Screenshot (62)

### CODE REVIEW

**Review by erickzhao — CHANGES_REQUESTED** [review]
these doc changes should not be committed

**Comment by Aryangp** [comment]
What's the problem pls tell

**Comment by erickzhao** [comment]
image

**Comment by Aryangp** [comment]
Hi erick I want to start contributing to electron js  i am new to open source .i know mern stack what else language should I learn for contributing to organisation

**Comment by erickzhao** [comment]
@Aryangp are you still interested in working on this? I would clean up the diff before I would consider this ready for review.

**Comment by Aryangp** [comment]
Yes i want to work on it

**Comment by erickzhao** [comment]
I'll leave this PR open then if you want to address the 197-file diff.

**Comment by dsanders11** [comment]
This was superseded by #461, so closing this out.

**Pull request closed without merging**
