### PR TITLE
feat: add navigation-history to examples sections on sidebar

### PR DESCRIPTION
**Pull request by alicelovescake**
This PR:
- [x] Adds `latest/tutorial/navigation-history` to sidebar since https://github.com/electron/electron/pull/42980 has merged

### CODE REVIEW

**Review by erickzhao — APPROVED** [review]

**Comment by ckerr** [comment]
I wonder what's going on with the `Cloudfire Pages` check hanging.

**Comment by MarshallOfSound** [comment]
The build is failing 🤷 

```

14:27:19.573 | - latest/tutorial/windows-taskbar
-- | --
14:27:19.573 |  
14:27:19.573 | at Object.checkSidebarsDocIds (/opt/buildhome/repo/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/utils.js:245:19)
14:27:19.573 | at doLoadVersion (/opt/buildhome/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:146:31)
14:27:19.573 | at async loadVersion (/opt/buildhome/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:163:28)
14:27:19.573 | at async Promise.all (index 0)
14:27:19.573 | at async Object.loadContent (/opt/buildhome/repo/node_modules/@docusaurus/plugin-content-docs/lib/index.js:171:33)
14:27:19.573 | at async /opt/buildhome/repo/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:39:23
14:27:19.573 | at async Promise.all (index 0)
14:27:19.573 | at async /opt/buildhome/repo/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:140:25
14:27:19.573 | at async loadSite (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/server/site.js:137:45)
14:27:19.574 | at async buildLocale (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:105:18)
14:27:19.574 | at async tryToBuildLocale (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:47:13)
14:27:19.574 | at async /opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:65:9
14:27:19.574 | at async mapAsyncSequential (/opt/buildhome/repo/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
14:27:19.574 | at async Command.build (/opt/buildhome/repo/node_modules/@docusaurus/core/lib/commands/build.js:63:5)
14:27:19.574 | }


```

**Comment by erickzhao** [comment]
The build is failing due to the updater bot not passing repo checks and the content not actually being updated: https://github.com/electron/website/actions/runs/10999832814

We can pull in the data manually for now, but this needs to be reset by an admin (made a #wg-infra thread on this yesterday).

**Comment by erickzhao** [comment]
Looks like we decided intentionally to not backport the contents of the PR to `32-x-y`: https://github.com/electron/electron/pull/43889#pullrequestreview-2322960107

I think it's valid to mark this as draft and wait for Electron 33 to land before adding this to the website :)

**Comment by alicelovescake** [comment]
> Looks like we decided intentionally to not backport the contents of the PR to `32-x-y`: [electron/electron#43889 (review)](https://github.com/electron/electron/pull/43889#pullrequestreview-2322960107)
> 
> I think it's valid to mark this as draft and wait for Electron 33 to land before adding this to the website :)

Ahh thanks Erick!! My bad for losing track of the releases. Thanks for the call out!

**Review by erickzhao — APPROVED** [review]

**Comment by erickzhao** [comment]
oh wait superseded by https://github.com/electron/website/commit/9ee726b015321972d1a793359d25a05d8776d4e7

**Pull request closed without merging**
